### ISSUE TITLE
5. Построение страницы узлового анализа в интерфейсе

### ISSUE THREAD

**Issue by IlyaTernovskiy** [IlyaTernovskiy/it-school#16]
Создать страницу в интерфейсе, которая содержит:
- сайдбар с вводом параметров
- кнопки "очистить" и "рассчитать"
- график, на котором отображаются кривые IPR и VLP (точка пересечения кривых выделена)
- таблица с расчитанным режимом работы скважины (забойное давление и дебит жидкости, соответствующие точке пересечения на графике)

Дизайн соответствует макету в фигме: https://www.figma.com/file/grpG2LwNtgEmiE30jXp3RP/%D0%A0%D0%B0%D1%81%D1%87%D1%91%D1%82-%D1%80%D0%B5%D0%B6%D0%B8%D0%BC%D0%B0-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D0%B4%D0%BE%D0%B1%D1%8B%D0%B2%D0%B0%D1%8E%D1%89%D0%B5%D0%B9-%D1%81%D0%BA%D0%B2%D0%B0%D0%B6%D0%B8%D0%BD%D1%8B?node-id=0%3A1

**Comment by Invinsarble27** [comment]
# ТК Отображение страницы узлового расчета

1. Перейти на страницу узлового анализа - отображается левый сайдбар с полями ввода входных параметров, график узлового анализа, таблица режима работы под графиком

2. Внести в поле "Диаметр ЭК" и "Диаметр НКТ" произвольное значение - значение отображается в поле

3) Нажать кнопку "Очистить" -  поля очищаются

4) Нажать кнопку "Рассчитать" - кнопка нажимается, вылезает предупреждение (данные не заполнены)
